on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Test
        run: |
          if [[ $GITHUB_REPOSITORY == 'parro-it/gomod' ]]; then
            echo Running on template repo
          else
            if [ ! -f initialization-running ]; then 
              go test -failfast -race ./...
              go get golang.org/x/lint/golint
              golint -set_exit_status ./...
              go vet ./...
            fi
          fi
      
#      - name: Test & publish code coverage
#        uses: paambaati/codeclimate-action@v2.7.5
#        env:
#          CC_TEST_REPORTER_ID: ${---{ secrets.CODE_CLIMATE_REPORTER_ID }}
#        with:
#          coverageCommand: go test -coverprofile=c.out ./...
#          prefix: github.com/{{.Author}}/{{.RepoName}}
#